# Generated by Django 5.0 on 2024-10-04 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AlterModelOptions(
            name='teamcaptain',
            options={'verbose_name': 'Капитан', 'verbose_name_plural': 'Капитаны'},
        ),
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_captain', to='registration.teamcaptain'),
            preserve_default=False,
        ),
    ]
