# Generated by Django 5.0 on 2024-10-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_participant_options_alter_team_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='captain',
        ),
    ]
